### ISSUE TITLE
Suggestion: run mode options at top menu

### ISSUE THREAD

**Issue by filipkotoucek** [prusa3d/Prusa-CW-Firmware#20]
Original issue created by: @Lichtjaeger

Hi, it is recommended to remove supports between drying and curing. Easy parts can be dried and cured in one go. After cleaning my tools I only need drying and to cure the junk on paper towels only curing is needed.
So you have to change the mode a lot but it is two layers deep hidden in the menu.
In my opinion, the modes should be at the main menu. Maybe direct as different start points.

**Comment by filipkotoucek** [comment]
Comment from: Patrick Vrancken
I fully agree with this proposal. changing the run mode is painful and it is not very logical regarding the after-print process.

**Comment by Lichtjaeger** [comment]
Thanks for forwarding. 😉

**Comment by dave-cz-** [comment]
I suggest to display quick mode selection after long press of the button. In that case, default run mode preset could be done from the menu as it is done now.

**Comment by tritol** [comment]
A long press on the home menu activates the mode change as in the settings. This choice has been there since the first release.

**Comment by MMetze** [comment]
You are right. So, essentially, this is all I needed, even better than a new top level menu item.
