### ISSUE TITLE
[Feature Request] Change Directions During Wash Cycle

### ISSUE THREAD

**Issue by BeldrothTheGold** [prusa3d/Prusa-CW-Firmware#29]
Make platform switch directions during wash cycle. 
Add an option to choose choose how many times the machine switches directions while washing.

**Comment by JakoobCZ** [comment]
Hi Beldroth,
thanks for the suggestion, I had a brief talk with the developer today about this feature. We will see, whether it can be implemented in the upcoming release.

**Comment by Saij** [comment]
I have implemented such feature in pull request #34 
It changes directions after a given amount of time. Also you are able to set the starting direction.

**Comment by BeldrothTheGold** [comment]
I know it's been quite a while since this was posted, are there any plans to merge the PR that Saij created. Or at least merging a similar feature? Having the IPA flow change directions really seems like it could significantly improve the efficiency of the CW1.

**Comment by tritol** [comment]
Yes, it will be included in next release.

**Comment by atiniir** [comment]
was this ever merged/implemented? i see the pull request is still open.

**Comment by BeldrothTheGold** [comment]
What's the status of this? What's holding up the release of this firmware update?
